### PR TITLE
Pull request for resolved prefix bug

### PR DESCRIPTION
**Pull request by tayfunhalac**
ResourceDescription class was returning describe query result model for
namespace prefixes. For this reason, reuslt page did not contain prefix
declarations and all prefixes was seen as question marks ("?"). Prefix
map of configuration should be returned from getPrefixes method instead
of model field.

### CODE REVIEW

**Comment by cygri** [comment]
Fixed in 48be88997. I couldn't apply your commit directly because you messed with the whitespace…

**Comment by tayfunhalac** [comment]
OK. You are right about my commit. Thank you for the fix.

**Comment by BarryNorton** [comment]
Looking at the development version of ResourceDescription.java is looks like prefixes are merged from the model (which I guess is formed from the DESCRIBE result) and the Configuration member. Still we're getting some of our resources with a ? as the prefix, even though the prefix is definitely defined (used for those very resources, in fact) in the DESCRIBE result. Any idea what could be going wrong?

**Comment by cygri** [comment]
Yes, that's how it's supposed to work (merge prefixes from DESCRIBE result and config.ttl, with the latter taking precedence). A couple of things to try:
1. Check Pubby's Turtle output to see what prefixes are used there.
2. Try adding one of the offending prefixes manually to the config to see what happens.
3. What exactly is the URI in question? Any unusual characters? Pubby implements its own logic for splitting off the local name (in `URIPrefixer.java`), and maybe it somehow tries to split the URI differently from the way you think.

**Comment by BarryNorton** [comment]
Sorry, resolved by building from source - I didn't realise how out of date the official build was

**Comment by cygri** [comment]
Ah, ok, and sorry for the lack of an up-to-date release! Glad it works now.

**Pull request closed without merging**
