### PR TITLE
Dynamic index resources

### PR DESCRIPTION
**Pull request by wikier**
patch for dynamically generate a list of all available resources when index is requested (and IndexResource is missing in the configuration)

### CODE REVIEW

**Comment by wikier** [comment]
Useful patch for us on some of our private deployments

**Comment by cygri** [comment]
Nice! This is much better than the current default behaviour when no index resource is set. A couple of points though:
- The `FIXME` should indeed be fixed. I think it could be done simply by checking the URI against the index address in `getResourceDescription()` rather than in `execDescribe()`.
- A note in the section on `conf:indexResource` in `doc/index.html` would be nice.
- `RDF.java` is unnecessary, a file with the same constants already ships with Jena.
- The icing on the cake would be paging of the resource list. Read a `?page=xxx` value from the request params and use it to set a `LIMIT`/`OFFSET` value? Probably means there should be `ORDER BY ?s` too.

**Comment by wikier** [comment]
I pushed new commits solving the first three comments. 

For the last one I'd need more time for diving deeper in the code, and find where/how should be the right way to add pagination only for the index resource without affect the main functionality and performance.

**Comment by wikier** [comment]
BTW, acknowledgement to the [ADAPTA](http://www.treelogic.com/web/guest/investigacion/tecnologias-semanticas/-/journal_content/56/10137/35701) research project, partially funded by the [INNPACTO 2011 programme](http://www.idi.mineco.gob.es/portal/site/MICINN/menuitem.dbc68b34d11ccbd5d52ffeb801432ea0/?vgnextoid=c8e371e47ecfe210VgnVCM1000001d04140aRCRD) (IPT-2011-0949-430000) of the Spanish Ministry of Science and Innovation and the European Regional Development Fund (FEDER).

**Comment by cygri** [comment]
Looks great @wikier! For pagination, the cleanest thing would probably be to add a separate IndexServlet that has the pagination, and forward from the RootServlet to the IndexServlet only if no `conf:indexResource` is set.

**Comment by wikier** [comment]
Right, maybe we should use to a separate servlet. The current implementation reuse the default rendering mechanism (both HTML and RDF) creating a fake resource `resource/Index`, which is of questionable accuracy.

I'll try to take a look on this issue during the week.

**Pull request merged**
